//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrance
    {
        public int IdRecord { get; set; }
        public System.DateTime DateEnt { get; set; }
        public decimal NumberEnt { get; set; }
        public string IdProvider { get; set; }
        public string ArticleCloth { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Sum { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
