//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricWarehouse
    {
        public int Roll { get; set; }
        public string FabricArticle { get; set; }
        public decimal Width { get; set; }
        public decimal Length { get; set; }
    
        public virtual Cloth Cloth { get; set; }
    }
}
