//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.ProductFittings = new HashSet<ProductFittings>();
            this.WarehouseOfFittings = new HashSet<WarehouseOfFittings>();
        }
    
        public string Article { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public decimal Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFittings> ProductFittings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseOfFittings> WarehouseOfFittings { get; set; }
    }
}
