//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFittings
    {
        public string ArticleOfFittings { get; set; }
        public string ProductNumber { get; set; }
        public string Placement { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Turn { get; set; }
        public int Quantity { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Product Product { get; set; }
    }
}
