//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseOfFittings
    {
        public int Party { get; set; }
        public string ArticleOfFittings { get; set; }
        public int Quantity { get; set; }
    
        public virtual Furniture Furniture { get; set; }
    }
}
